version: 2
jobs:
  build:
    docker:
      - image: golang
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pirsch
    working_directory: /go/src/github.com/emvi/pirsch
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: apt-get update && apt-get install postgresql-client -y
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: psql -h localhost -p 5432 -U postgres < /go/src/github.com/emvi/pirsch/schema/postgres/schema.sql
      - run: psql -h localhost -p 5432 -U postgres < /go/src/github.com/emvi/pirsch/schema/postgres/v1.2.0.sql
      - run: go test -cover .
